CREATE TABLE public.sets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    title TEXT NOT NULL,
    description TEXT,
    category TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE public.cards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    set_id BIGINT NOT NULL
        REFERENCES public.sets(id)
        ON DELETE CASCADE,

    front TEXT NOT NULL,
    back TEXT NOT NULL,
    example TEXT,
    meaning TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

